django_app/django_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('people.urls')),
    url(r'^admin/', admin.site.urls),
]

django_app/people/urls.py
from django.conf.urls import url
from . import views

app_name = 'people'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^list/$', views.list, name='list'),
    url(r'^add/$', views.add, name='add'),
]

django_app/people/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Person(models.Model):
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)

django_app/people/forms.py
from django import forms

class AddPersonForm(forms.Form):
    name = forms.CharField(label="Name", max_length=255, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label="Email", max_length=255, widget=forms.TextInput(attrs={'class': 'form-control'}))

django_app/people/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse

from .forms import AddPersonForm
from .models import Person

# Create your views here.

def index(request):
    return render(request, 'people/index.html')
    
def list(request):
    people = Person.objects.all()
    return render(request, 'people/list.html', {'people': people})
    
def add(request):
    if request.method == 'POST':
        form = AddPersonForm(request.POST)
        if form.is_valid():
            person = Person(name=form.cleaned_data['name'], email=form.cleaned_data['email'])
            person.save()
            return HttpResponseRedirect(reverse('people:list'))
    else:
        form = AddPersonForm()
         
    return render(request, 'people/add.html', {'form': form})

django_app/people/templates/people/add.html
{% extends 'people/layout.html' %}

{% block content %}

<h1>Add person</h1>

<form action="{% url 'people:add' %}" method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {% for field in form %}
        <div class="form-group">
            {{ field.label_tag }}
            {{ field }}
            {% if field.help_text %}
                <p class="help-block">{{ field.help_text|safe }}</p>
            {% endif %}
            {% if field.errors %}
                {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                {% endfor %}
            {% endif %}
        </div>
    {% endfor %}
    <input type="submit" class="btn btn-default" value="Save" />
</form>

{% endblock %}

django_app/people/templates/people/index.html
{% extends 'people/layout.html' %}

{% block content %}

<h1>Django Challenge @ Seedstars</h1>

<p>
    Welcome to the Django Challenge web app proposed by Seedstars. This is a simple web app where you have
    a list of names and emails stored in a SQLite database. You can add new entries or view existing ones.
</p>

<div class="panel panel-default">
    <div class="panel-heading">Actions</div>

    <div class="list-group">
        <a href="{% url 'people:list' %}" class="list-group-item">List people</a>
        <a href="{% url 'people:add' %}" class="list-group-item">Add person</a>
    </div>
</div>



{% endblock %}

django_app/people/templates/people/layout.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Django Challenge - Seedstars{% endblock %}</title>
    
    <link rel="stylesheet" type="text/css" href="{% static 'people/bootstrap/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'people/bootstrap/css/bootstrap-theme.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'people/style.css' %}" />
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'people:index' %}">Django Challenge</a>
            </div>

            <div class="collapse navbar-collapse" id="navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'people:index' %}">Home</a></li>
                    <li><a href="{% url 'people:add' %}">Add person</a></li>
                    <li><a href="{% url 'people:list' %}">List people</a></li>
                </ul>
            </div>
        </div>
    </nav>
    
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    
    <footer>
        Daniel Filipe Silva -
        <a href="mailto:danfilipesilva@gmail.com">Email</a> |
        <a href="https://pt.linkedin.com/in/dfilipes" target="_blank">LinkedIn</a> |
        <a href="https://github.com/DFilipeS" target="_blank">GitHub</a> |
        <a href="http://www.dfilipes.com" target="_blank">Website</a>
    </footer>
    
    <script src="{% static 'people/jquery.min.js' %}"></script>
    <script src="{% static 'people/bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

django_app/people/templates/people/list.html
{% extends 'people/layout.html' %}

{% block content %}

<h1>List people</h1>

{% if people %}
    <p class="pull-right">
        <a href="{% url 'people:add' %}" class="btn btn-default">Add person</a>
    </p>
    
    <table class="table table-bordered table-hover">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Email</th>
    </tr>
    {% for person in people %}
        <tr>
            <td>{{ person.id }}</td>
            <td>{{ person.name }}</td>
            <td>{{ person.email }}</td>
        </tr>
    {% endfor %}
</table>
{% else %}
    <p>There are no people on record. Why not <a href="{% url 'people:add' %}">add</a> some now?</p>
{% endif %}

{% endblock %}